name: Regular Template Validation

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository for creating issues'
        required: false
      create_issue:
        description: 'Create issue if validation fails'
        default: false
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 UTC on the first day of every month

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.list-templates.outputs.repositories }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: List templates
        id: list-templates
        working-directory: website/static
        run: |
          repositories=`jq -r '.[] | .source' templates.json | jq -Rsc '[split("\n") | .[]| select(.!="")]'`
          echo "repositories=$repositories" >> $GITHUB_OUTPUT

  validate-templates:
    if: ${{ needs.setup.outputs.repositories }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.setup.outputs.repositories) }}
      max-parallel: 1
    name: ${{ matrix.repo }} 
    env:
      # For azd login
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      # OIDC token is not working for Terraform, so we need to use the client secret. Figure out a way to use OIDC token.
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      # For Terraform backend
      RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
      RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
      RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
      # template specific variables
      AZURE_DOCUMENTINTELLIGENCE_LOCATION: ${{ vars.AZURE_DOCUMENTINTELLIGENCE_LOCATION }}
      AZURE_OPENAI_LOCATION: ${{ vars.AZURE_OPENAI_LOCATION }}
      MOCKED_OPENAI_API_KEY: ${{ vars.MOCKED_OPENAI_API_KEY }}

    steps:
      - name: Install AZD
        uses: Azure/setup-azd@v1.0.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/validator/requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clone repo
        working-directory: ${{ runner.temp }}
        run: |
          git clone ${{ matrix.repo }} template
          candidate_hooks_paths=("./template/hooks" "./template/infra/hooks" "./template/scripts")

          for hooks_path in "${candidate_hooks_paths[@]}"; do
            if [ -d "$hooks_path" ] && [ "$(ls -A $hooks_path/*.sh 2>/dev/null)" ]; then
              chmod +x $hooks_path/*.sh
              echo "Executable permissions set for .sh files in $hooks_path"
            else
              echo "No hooks directory or no .sh files found in $hooks_path"
            fi
          done

          if [ -f "./template/package.json" ]; then
            echo "Installing npm dependencies"
            cd template
            npm install
          fi

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@v1
        id: msdo
        env:
          GDN_TEMPLATEANALYZER_ANALYZEDIRECTORY: ${{ runner.temp }}/template
        with:
          tools: templateanalyzer
        continue-on-error: true
      
      - name: Extract repo name
        id: extract_repo_name
        run: |
          repo_name=$(echo ${{ matrix.repo }} | sed -E 's|https://github.com/([^/]+/[^/]+).*|\1|')
          repo_name_short=${repo_name##*/}
          echo "REPO_NAME=$repo_name" >> $GITHUB_OUTPUT
          echo "REPO_NAME_SHORT=$repo_name_short" >> $GITHUB_OUTPUT

      - name: Get repository topics
        id: get_repo_topics
        env:
          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}
          REPO_NAME: ${{ steps.extract_repo_name.outputs.REPO_NAME }}
        run: |
          topics_list=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ env.REPO_NAME }}/topics | jq -r '.names | join(",")')
          echo "topics=\"$topics_list\"" >> $GITHUB_ENV

      - name: Set environment name with job id
        run: |
          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
          env_name="${{ vars.AZURE_ENV_NAME }}$job_id"
          echo "AZURE_ENV_NAME=$env_name" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh
      
      - name: Run validation
        working-directory: ${{ runner.temp }}/template
        run: |
          python ${{ github.workspace }}/.github/validator/validator.py . --azdup --azddown --output ../output.log --topics ${{ env.TOPICS }} --msdoresult ${{ steps.msdo.outputs.sarifFile }} --debug
        env:
          AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
          OPENAI_API_KEY: ${{ env.MOCKED_OPENAI_API_KEY }}
          CREATE_ROLE_FOR_USER: false
          AZD_PREPDOCS_RAN: "false"
          SERVICE_API_RESOURCE_EXISTS: "false"
          TOPICS: ${{ env.topics }}

      - name: Create or update issue if failed
        if: github.event.inputs.create_issue == 'true'
        working-directory: ${{ runner.temp }}
        run: |
          repo="${{ matrix.repo }}"
          issue_number=$(gh issue list --author "ai-apps-bot" --repo "$repo" --json number | jq -r '.[0].number')
          if grep -q "FAILED" output.log; then
            echo "Validation failed, creating issue"
            if [ "null" == $issue_number ]; then
              gh issue create --title "[Auto] AI Gallery Standard Validation FAILED" --body-file output.log --repo $repo
            else
              gh issue edit $issue_number --body-file output.log --repo $repo
            fi
          else
            echo "Validation passed, close opened issue"
            if [ "null" != $issue_number ]; then
              gh issue edit $issue_number --body-file output.log --repo $repo
              gh issue close $issue_number --repo $repo --reason "Validation passed"
            fi
          fi
        env: 
          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}

      - name: Add repo name to output
        run: |
          echo -e "\n# Repo: ${{ steps.extract_repo_name.outputs.REPO_NAME }}\n" >> ${{ runner.temp }}/output.md
          cat ${{ runner.temp }}/output.log >> ${{ runner.temp }}/output.md

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_repo_name.outputs.REPO_NAME_SHORT }}
          path: ${{ runner.temp }}/output.md

  merge-result:
    if: ${{ always() }}
    needs:
      - validate-templates
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: merged-results

      - name: Summarize
        working-directory: merged-results
        run: |
          total=0
          failed=0
          failed_repos=""
          for file in $(ls */output.md); do
            total=$((total + 1))
            if grep -q "FAILED" "$file"; then
              failed=$((failed + 1))
              folder=$(dirname "$file")
              failed_repos="${failed_repos}\n${folder}"
            fi
          done
          echo -e "# Validation Summary\n"
          echo -e "Failed/Total: $failed/$total\nFailed Repos:${failed_repos}\n" >> summary.md
          cat ./*/output.md >> summary.md

      - name: Find existing issue
        if: github.event.inputs.create_issue == 'true'
        id: find-existing-issue
        run: |
          repo="${{ github.event.inputs.repository || github.repository }}"
          issue_number=$(gh issue list --author "ai-apps-bot" --repo "$repo" --json number | jq -r '.[0].number')
          echo "issue_number=$issue_number" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}

      - name: Create or update summary issue
        if: github.event.inputs.create_issue == 'true'
        working-directory: merged-results
        run: |
          repo="${{ github.event.inputs.repository || github.repository }}"
          issue_number="${{ steps.find-existing-issue.outputs.issue_number }}"
          if [ "null" == $issue_number ]; then
            gh issue create --title "Templates Validation Summary" --body-file summary.md --repo $repo
          else
            gh issue edit $issue_number --body-file summary.md --repo $repo
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}

      - name: Upload merged results
        uses: actions/upload-artifact@v4
        with:
          name: 0.merged-results
          path: merged-results/summary.md
